[build]
  functions = "netlify/functions" 
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200
  conditions = { Language = ["en"] } 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
#   # /////
# [[redirects]]
#   from = "https://scutigera.online/*"
#   to = "https://www.scutigera.online/:splat"
#   status = 301
#   force = true
# [[redirects]]
#   from = "https://www.scutigera.online"
#   to = "https://scutigera.online"
#   status = 301
#   force = true