[build]
  functions = "netlify/functions" 
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200
  conditions = { Language = ["en"] } 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200